/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPostsIdIndexRouteImport } from './routes/admin/posts/[id]/index'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin/posts/[id]/edit'
import { Route as AdminPostsIdTestRouteImport } from './routes/admin/posts/[id]/_test'

const AdminRouteImport = createFileRoute('/admin')()
const AdminPostsIdRouteImport = createFileRoute('/admin/posts/id')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/id',
  path: '/posts/id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdIndexRoute = AdminPostsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsIdRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPostsIdRoute,
} as any)
const AdminPostsIdTestRoute = AdminPostsIdTestRouteImport.update({
  id: '/_test',
  getParentRoute: () => AdminPostsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/posts/id': typeof AdminPostsIdTestRoute
  '/admin/posts/id/edit': typeof AdminPostsIdEditRoute
  '/admin/posts/id/': typeof AdminPostsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/posts/id': typeof AdminPostsIdIndexRoute
  '/admin/posts/id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_layout': typeof authLayoutRoute
  '/(auth)/login': typeof authLoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/posts/id': typeof AdminPostsIdRouteWithChildren
  '/admin/posts/id/_test': typeof AdminPostsIdTestRoute
  '/admin/posts/id/edit': typeof AdminPostsIdEditRoute
  '/admin/posts/id/': typeof AdminPostsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/media'
    | '/admin/'
    | '/admin/posts/create'
    | '/admin/posts'
    | '/admin/posts/id'
    | '/admin/posts/id/edit'
    | '/admin/posts/id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/media'
    | '/admin/posts/create'
    | '/admin/posts'
    | '/admin/posts/id'
    | '/admin/posts/id/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_layout'
    | '/(auth)/login'
    | '/admin'
    | '/admin/_layout'
    | '/admin/media'
    | '/admin/'
    | '/admin/posts/create'
    | '/admin/posts/'
    | '/admin/posts/id'
    | '/admin/posts/id/_test'
    | '/admin/posts/id/edit'
    | '/admin/posts/id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRoute
  authLoginRoute: typeof authLoginRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/id': {
      id: '/admin/posts/id'
      path: '/posts/id'
      fullPath: '/admin/posts/id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/id/': {
      id: '/admin/posts/id/'
      path: '/'
      fullPath: '/admin/posts/id/'
      preLoaderRoute: typeof AdminPostsIdIndexRouteImport
      parentRoute: typeof AdminPostsIdRoute
    }
    '/admin/posts/id/edit': {
      id: '/admin/posts/id/edit'
      path: '/edit'
      fullPath: '/admin/posts/id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminPostsIdRoute
    }
    '/admin/posts/id/_test': {
      id: '/admin/posts/id/_test'
      path: '/posts/id'
      fullPath: '/admin/posts/id'
      preLoaderRoute: typeof AdminPostsIdTestRouteImport
      parentRoute: typeof AdminPostsIdRoute
    }
  }
}

interface AdminPostsIdRouteChildren {
  AdminPostsIdTestRoute: typeof AdminPostsIdTestRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
  AdminPostsIdIndexRoute: typeof AdminPostsIdIndexRoute
}

const AdminPostsIdRouteChildren: AdminPostsIdRouteChildren = {
  AdminPostsIdTestRoute: AdminPostsIdTestRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
  AdminPostsIdIndexRoute: AdminPostsIdIndexRoute,
}

const AdminPostsIdRouteWithChildren = AdminPostsIdRoute._addFileChildren(
  AdminPostsIdRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRoute,
  authLoginRoute: authLoginRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
